# -*- coding: utf-8 -*-
"""ManipulationFilesLAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7Sfjoy13QwDGrfCI8kOX7tSXo3el3OX
"""

#https://lasio.readthedocs.io/en/latest/pandas.html
#https://lasio.readthedocs.io/en/latest/exporting.html#comma-separated-values-csv

!pip install lasio

# Libraries for data loading
import lasio
import pandas as pd
import os

# Libraries for data visualization:
import matplotlib.pyplot as plt
import seaborn as sns

lasFile = lasio.read('/content/sample_data/DataFilesLAS/1.2/2003.las')
df = lasFile.df()
print(df)

lasFile.version

df.head(10)

df.tail(20)

df.describe()

lasFile = lasio.read('/content/sample_data/DataFilesLAS/2.0/15580.las')
df = lasFile.df()
print(df)

# Creating Histograms Using pandas
df['GK'].plot(kind='hist')
plt.show()

# Creating Histograms Using matplotlib
plt.hist(df['GK'])
plt.show()

plt.hist(df['GK'], bins=30, edgecolor='black')
plt.show()

plt.hist(df['GK'], bins=30, color='red', alpha=0.5, edgecolor='black')
plt.xlabel('Gamma Ray - API', fontsize=14)
plt.ylabel('Frequency', fontsize=14)
plt.xlim(0,30)

plt.savefig('histogram.png', dpi=300)

plt.show()

df['GK'].plot(kind='hist', bins=30, color='blue', alpha=0.5, density=True, edgecolor='black')
df['GK'].plot(kind='kde', color='black')
plt.xlabel('Gamma Ray - API', fontsize=14)
plt.ylabel('Density', fontsize=14)
plt.xlim(0,30)

plt.legend()

# Creating a Simple Line Plot
df.plot('GK', 'BK')

df.plot(subplots=True, figsize=(15, 15))

# Subplots in Matplotlib
fig = plt.subplots(figsize=(10,10))

#Set up the plot axis
ax1 = plt.subplot2grid((1,1), (0,0), rowspan=1, colspan = 1) 

ax1.plot("GK", "BK", data = df, color = "green") # Call the data from the df dataframe
ax1.set_xlabel("Gamma") # Assign a track title
ax1.set_xlim(0, 20) # Change the limits for the curve being plotted
ax1.set_ylim(100, 50) # Set the depth range
ax1.grid() # Display the grid

# Adding the Density Log

fig = plt.subplots(figsize=(10,10))

#Set up the plot axes
ax1 = plt.subplot2grid((1,3), (0,0), rowspan=1, colspan = 1) 
ax2 = plt.subplot2grid((1,3), (0,1), rowspan=1, colspan = 1)


ax1.plot("GK", "BK", data = df, color = "green") # Call the data from the well dataframe
ax1.set_xlabel("Gamma") # Assign a track title
ax1.set_xlim(0, 20) # Change the limits for the curve being plotted
ax1.set_ylim(100, 50) # Set the depth range
ax1.grid() # Display the grid

ax2.plot("PS", "BK", data = df, color = "red")
ax2.set_xlabel("Deep Res.")
ax2.set_xlim(0.2, 20)
ax2.semilogx()
ax2.set_ylim(100, 50)
ax2.grid()

# Read the Files

las_file_list = []
path = "/content/sample_data/DataFilesLAS/1.2/"


# View contents of the path, we will see LAS files plus an ASCII file
files = os.listdir(path)
files

dflist = []

for lasfile in las_file_list:
    las = lasio.read(lasfile)
    lasdf = las.df()
    
    lasdf['WELL'] = las.well.WELL.value
    lasdf['DEPTH'] = lasdf.index
    dflist.append(lasdf)
    dflist.sort(lasdf)